[package]
name = "pman-desktop"
version = "0.4.1"
description = "pman local credential boundary desktop client"
authors = ["pman contributors"]
edition = "2021"

[lib]
name = "pman_desktop_lib"
crate-type = ["staticlib", "cdylib", "rlib"]

[build-dependencies]
tauri-build = { version = "2.0", features = [] }

[dependencies]
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
tauri = { version = "2.0", features = ["tray-icon"] }
pman-core = { path = "../../rust/crates/pman-core" }
zeroize = "1.8"
rand = "0.8"
hex = "0.4"
sha2 = "0.10"
uuid = { version = "1", features = ["v4"] }
chrono = { version = "0.4", default-features = false, features = ["clock"] }
toml = "0.9"
rusqlite = { version = "0.32", features = ["bundled", "backup"] }

[target.'cfg(windows)'.dependencies]
webview2-com = "0.38"
windows = { version = "0.61", features = ["Security_Credentials_UI", "Win32_System_WinRT", "Win32_System_Registry", "Win32_System_RemoteDesktop", "Win32_System_SystemInformation", "Win32_System_DataExchange", "Win32_System_Memory", "Win32_UI_Input_KeyboardAndMouse", "Win32_UI_Shell", "Win32_UI_WindowsAndMessaging", "Win32_Foundation", "Win32_Storage_FileSystem", "Win32_Security", "Win32_System_Threading", "UI_Notifications", "Data_Xml_Dom", "Win32_UI_Controls_Dialogs", "Win32_System_Com", "Win32_System_Com_StructuredStorage", "Win32_System_Variant", "Win32_UI_Shell_PropertiesSystem", "Win32_Storage_EnhancedStorage"] }
windows-future = "0.2"

[dev-dependencies]
tempfile = "3"
